baseURL = 'https://centre-for-music-and-science.github.io/'
languageCode = 'en-gb'
title = 'Centre for Music and Science'
theme = 'cms'

[params]
  description = "The Centre for Music and Science (CMS) supports both teaching and research into the science of music at the University of Cambridge."
  heroTitle = "Centre for Music and Science"
  heroSubtitle = "University of Cambridge"
  themesIntro = "We conduct groundbreaking scientific and computational research into music, which we see as a complex phenomenon deriving from interactions between the physics of sound, the biology of the human auditory system, the psychology of the human mind, and the dynamics of human society."

buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
