baseURL = 'https://centre-for-music-and-science.github.io/'
languageCode = 'en-gb'
title = 'Centre for Music and Science'
theme = 'cms'

[params]
  description = "The Centre for Music and Science (CMS) supports both teaching and research into the science of music at the University of Cambridge."
  heroTitle = "Centre for Music and Science"
  heroSubtitle = "University of Cambridge"
  themesIntro = "Our research spans multiple disciplines, combining computational, cognitive, and empirical approaches to understand music and its role in human life."

buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
